### PR TITLE
Update gleam import and web export to support cities

### PR DESCRIPTION
**Pull request by gavento**
General
* `read_csv_smart` optionally prefers larger regions
* Fixed broken pandas Region display
* Fix DisplayName (contained "nan" for some basins)
Update gleam import
* Add overwrite option
* Make work for gleam basins (cities)
* Ignore missing initial_compartments
Update web export
* Mathij's many updates from #44 (cherry-picked)
* Ignore cities missing M49
* Ignore empty TZ list

### CODE REVIEW

**Comment by gavento** [comment]
@mathijshenquet I would like to merge this to master. Could you take a look at changes to export (mostly yours, very few mine) and check that they do not break the main workflow, and finish any cleanups etc.?
(Or let me know that this is only throwaway code - I also added some useful/general features/fixes that would need separation on my side.)

**Comment by gavento** [comment]
@mathijshenquet I would like to merge this to master. Could you take a look at changes to export (mostly yours, very few mine) and check that they do not break the main workflow, and finish any cleanups etc.? 
(Or let me know that this is only throwaway code - I also added some useful/general features/fixes that would need separation on my side.)

**Comment by gavento** [comment]
Note: two commit 4122e7da2b1dc86f4157c3ee2538a2bf8eab2b83 should be also part of this but was pushed to master by mistake. (But it is functional on its own)

**Review by mathijshenquet — APPROVED** [review]
Looks good to me and tested on master

**Review by hnykda — APPROVED** [review]

**Pull request merged**
