### PR TITLE
Incorporating Balochistan workflow to master

### LINKED ISSUE #452: Problem: Balochistan customsite does not have a reproducable build

### PR DESCRIPTION
**Pull request by mathijshenquet**
Resolves https://github.com/epidemics/covid/issues/452

- Allow overwriting region names in `config.yml`
- Add Balochistan data to `sites/balochistan/`
- Moves data to generated the main site to `sites/main/`
- Made it possible to specify in `config.yaml` and `estimates.csv` when the model was updated/when the estimates were made.

NB: The `sites/` directory would be how I would organize the different sites going forward.

Blocked by https://github.com/epidemics/epimodel/pull/49

### CODE REVIEW

**Comment by mathijshenquet** [comment]
Does someone know a better/cleaner way to take care of the custom names?

**Comment by hnykda** [comment]
I believe this is superseded by switching to luigi. The way how this could be changed is by providing a different `data-dir` (or just it outputs directory) https://epidemicforecasting.slack.com/archives/CV93A58G7/p1590040992047800?thread_ts=1590019434.047600  . You can then have a config per site (or just provide the parameter on CLI)

Should I document it?

**Comment by hnykda** [comment]
I tried to document how to have config per locations: https://github.com/epidemics/epimodel/commit/02883a7195a6a35a990e61c9da4193accb53f11f .

Other than that, I think that the PR looks generally good. Does anyone have resources to rebase it to current master with luigi? I think the steps would be to:

1. move the data to https://github.com/epidemics/epimodel/tree/master/data-dir/inputs, directory `balochistan` (`sites` is also fine, but ideally consistent...)
2. move the parameters from `config.yaml` to a luigi-compatible `balochistan.cfg` as documented in the [commit above](https://github.com/epidemics/epimodel/commit/02883a7195a6a35a990e61c9da4193accb53f11f) (e.g. gleam_resample and so on)
3. keep the actual business logic changes as is in this PR

**Comment by mathijshenquet** [comment]
I will do that

**Comment by hnykda** [comment]
Cool. Any ETAs?

**Comment by mathijshenquet** [comment]
With [this commit](https://github.com/epidemics/epimodel/commit/f2a219029dc80d4babc061a64c83dd3a2478fa09) it has become impossible to reproduce the website builds using the hdf5 files in `fixtures`. The reason is the reworking of how the trace/group names work and how it expects the traces to be named in `hdf5` and how it puts them in the exported json file.

The breakage for the normal site, renamed `main` here, is limited and I will make a issue about it - https://github.com/epidemics/covid/issues/459. For balochistan it might be more severe and I have no idea how to approach it at this point.

**Comment by hnykda** [comment]
And do we still need it?

**Pull request closed without merging**
