### PR TITLE
Cleanup WebExport

### LINKED ISSUE #410: replace "models_df" by "cummulative_df"
Solve this todo: https://github.com/epidemics/epimodel/blob/83f9bdd33a567d97b3b28904ac9fdef95a0831ab/epimodel/exports/epidemics_org.py#L485

### LINKED ISSUE #442: Cleanup v3 backend
Blocking #403

### PR DESCRIPTION
**Pull request by mathijshenquet**
- Remove V3 traces, fixes https://github.com/epidemics/covid/issues/442
- In data verification `models_df -> cummulative_active_df`, fixes https://github.com/epidemics/covid/issues/410
- Remove time part for traces
- Replace floats for ints in exported json for population and JH data (verified to work)
- Add typings

### CODE REVIEW

**Comment by mathijshenquet** [comment]
Ping @gavento / @hnykda / @wolverdude for review

**Review by hnykda — APPROVED** [review]

**Comment by hnykda** [comment]
Looks good, thanks. Appreciate the types :-) .

**Comment by hnykda** [comment]
Also, I don't need additional ping if I am marked as reviewer (have notifications).

**Comment by euanong** [comment]
Sorry if this seems overly pedantic, but I think it's spelt `cumulative` rather than `cummulative` https://dictionary.cambridge.org/dictionary/english/cumulative (I imagine this could potentially lead to annoying bugs)

**Comment by mathijshenquet** [comment]
I had also spotted this but: 
- the epimodel function is written like that
- refactoring this felt out of scope for this PR
- I didn't want to rename the df variable for consistency

**Comment by euanong** [comment]
@mathijshenquet ah, understood 👍

**Pull request merged**
