### PR TITLE
Improve web-export

### PR DESCRIPTION
**Pull request by mathijshenquet**
- add rates
- snake case for json exports

### CODE REVIEW

**Comment by hnykda** [comment]
This is not a problem of this PR per se, but more like a consequence of the design. I would personally aim for a situation, where we have a single data blob (be it a python object, dict-like structure, (set of) dataframe(s)), have it all loaded at once and then serializing it. 

Right now it seems we are loading everything during serializing never having everything at once place, making debugging much harder. I don't think the datasize is an issue, it's small and can be all in memory just fine.

**Comment by gavento** [comment]
What do you mean, @hnykda? Are you talking about single DataFrame? Single source CSV file? ...

**Comment by gavento** [comment]
@mathijshenquet Thanks for the PR. Few points:

Why create a separate class for hospital rates? If the rates would be stored as CSV/HDF5 indexed by `Code` (the canonical code in epimodel), you'd only need to add df = read_csv('hspital-beds.csv').

* This is not scalable to do for all the things we want to add.
* Similarly, I would prefer not to have additional arguments for every data source added, and being present in many places throughout the code.
* Why underscore? Is it not just cosmetic? (May be good to have consistency with the source CSVs, for anyone coming into it etc. (I also like the all the CamelCased names are data properties, currently.)

Why not add a method that takes a series/dataframe and adds all the selected columns to the regions already in a given WebExport? Then `do` could look like:

```python
def web_export(args):
    ex = WebExport(comment=args.comment)
    for code in args.config["export_regions"]:
        ex.new_region(args.rds[code])

    rates = epimodel.read_csv('data/hospital-rates.csv')
    ex.add_data_from(rates, columns=['A', 'B'])  ## new function that goes through existing regions, maybe warns on missing data?

    # Similarly for series data with `Date`:
    jh = epimodel.read_csv('data/john-hopkins.csv')
    ex.add_data_from(jh, columns=['Confirmed'])

    # Dataframes with `Date` multiindex can be autodetected by `add_data_from`,
    # (that is robust to detect) or there can be a separate function for that.

    # TODO: add more data to ex
    ex.write(args.config["output_dir"])

```

@mathijshenquet Would you write such function?

Also, it wold be good to have a common format for series and graphs. Leaving for discussion with @hnykda ..

**Exports:** exports being all named differently is by design and I would not drop it without further discussion (let me know if there is already some more reasoning there):
* You can already add name as a suffix comment (for info)
* You can revert to an older dataset by re-uploading it
* While uploading, nobody can see inconsistent state, as the main file (pointing to the subdir) is replaced last and atomically.

**Comment by gavento** [comment]
@mathijshenquet I think this would be better if it was in 2+ PRs (e.g. naming separate from fixing Levels and rates export)

**Comment by gavento** [comment]
@mathijshenquet thanks for fixing Level export, by the way!

**Comment by mathijshenquet** [comment]
Re: Export to folder/overwriting. It is not removed, only if you set -n/--name flag. I found this easier for debugging.

**Comment by hnykda** [comment]
So some scaffolding done for this in https://github.com/epidemics/epimodel/pull/25/

**Comment by hnykda** [comment]
Replaced by https://github.com/epidemics/epimodel/pull/25

**Pull request closed without merging**
