### PR TITLE
Add scenarios (/ scenario group) to extdata

### PR DESCRIPTION
**Pull request by mathijshenquet**

### CODE REVIEW

**Comment by mathijshenquet** [comment]
This should probably be merged as its used to build production

**Comment by hnykda** [comment]
if it's in production, let's merge it, but I dislike the fact that "data scenarios" are now detached from the "groups", will create a follow up ticket.

**Comment by hnykda** [comment]
https://github.com/epidemics/covid/issues/405

**Comment by mathijshenquet** [comment]
I dont understand what you mean. It was already like this, I just added the `name` and `description` fields.

**Comment by hnykda** [comment]
You are right, it's apparently late enough for me, I understood it wrong...

**Comment by hnykda** [comment]
I am going to merge it as I am going to work on https://github.com/epidemics/covid/issues/399 so would like to prevent conflicts.

**Pull request merged**
