### PR TITLE
[DO NOT MERGE] adding autoupdating pipeline as kubernetes cronjob

### PR DESCRIPTION
**Pull request by hnykda**
Solves https://github.com/epidemics/covid/issues/393

This is an example of what would have to be done and how it would roughly work. I promised to make a draft for @mathijshenquet to see. Ideas welcome.

### CODE REVIEW

**Comment by gavento** [comment]
@hnykda How about using github actions?
* [They do support cron](https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule) and [commit back](https://github.com/stefanzweifel/git-auto-commit-action) (just picked a random implementation there)
* We already have the GH action scripts to set up the project environment :grin: 
* You can inspect the ran jobs directly in GH
* Setting up messaging about failed jobs should be easy (directly in GH)

**Comment by mathijshenquet** [comment]
How resource constraint are we with github actions? I think GH actions are nice but if we want to do stuff like running notebooks (for example the counter measures notebook) it might be good to start with gcloud right away.

**Comment by hnykda** [comment]
@gavento I mentioned that on the original issue https://github.com/epidemics/covid/issues/393#issuecomment-615930811: 

> We would have to decide what's better (if GH actions or k8s)

and comment earlier:

>  [...] But no problem trying it via actions first too.

Depends on the workload, similarly to what Mathijs wrote. I think for now we are still fine with the [default GH resources](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources) given our tasks are quite light weight. k8s brings more flexibility for the price of complexity.

Feel free to close if implemented via actions.

**Comment by gavento** [comment]
Either is fine with me, I do not understand this technology so can't give much input here.

**Comment by hnykda** [comment]
I am going to close this and we can reopen when we actually want to run these jobs.

**Pull request closed without merging**
